name: auctave_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  intl: ^0.20.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/filter_categories_icons/
    - assets/illustrations/
    - assets/logos/
    - assets/dummy/
